// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYVaDlseADfha9Vc1ePm3VFiC1MFi8lAI',
    appId: '1:952534558204:web:389dc172cdf392fd4bfe79',
    messagingSenderId: '952534558204',
    projectId: 'kindacode-5f082',
    authDomain: 'kindacode-5f082.firebaseapp.com',
    storageBucket: 'kindacode-5f082.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIp-A3a6mlICWWxp6Drkf-xoJ8RnZTV-E',
    appId: '1:952534558204:android:e110b61e624aff714bfe79',
    messagingSenderId: '952534558204',
    projectId: 'kindacode-5f082',
    storageBucket: 'kindacode-5f082.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLNqc8iytSSChD6i5-bbd-8AbfhgTpH3c',
    appId: '1:952534558204:ios:aac374ae43c6a8714bfe79',
    messagingSenderId: '952534558204',
    projectId: 'kindacode-5f082',
    storageBucket: 'kindacode-5f082.appspot.com',
    iosBundleId: 'com.example.myfirebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLNqc8iytSSChD6i5-bbd-8AbfhgTpH3c',
    appId: '1:952534558204:ios:f05b8a76b470f1ff4bfe79',
    messagingSenderId: '952534558204',
    projectId: 'kindacode-5f082',
    storageBucket: 'kindacode-5f082.appspot.com',
    iosBundleId: 'com.example.myfirebaseproject.RunnerTests',
  );
}
